const states = {
    'alabama'             :  'AL' ,
    'alaska'              :  'AK' ,
    'america samoa'       :  'AS' ,
    'arizona'             :  'AZ' ,
    'arkansas'            :  'AR' ,
    'california'          :  'CA' ,
    'colorado'            :  'CO' ,
    'connecticut'         :  'CT' ,
    'delaware'            :  'DE' ,
    'district of columbia':  'DC' ,
    'micronesia'          :  'FM' ,
    'florida'             :  'FL' ,
    'georgia'             :  'GA' ,
    'guam'                :  'GU' ,
    'hawaii'              :  'HI' ,
    'idaho'               :  'ID' ,
    'illinois'            :  'IL' ,
    'indiana'             :  'IN' ,
    'iowa'                :  'IA' ,
    'kansas'              :  'KS' ,
    'kentucky'            :  'KY' ,
    'louisiana'           :  'LA' ,
    'maine'               :  'ME' ,
    'marshall islands'    :  'MH' ,
    'maryland'            :  'MD' ,
    'massachusetts'       :  'MA' ,
    'michigan'            :  'MI' ,
    'minnesota'           :  'MN' ,
    'mississippi'         :  'MS' ,
    'missouri'            :  'MO' ,
    'montana'             :  'MT' ,
    'nebraska'            :  'NE' ,
    'nevada'              :  'NV' ,
    'new hampshire'       :  'NH' ,
    'new jersey'          :  'NJ' ,
    'new mexico'          :  'NM' ,
    'new york'            :  'NY' ,
    'north carolina'      :  'NC' ,
    'north dakota'        :  'ND' ,
    'ohio'                :  'OH' ,
    'oklahoma'            :  'OK' ,
    'oregon'              :  'OR' ,
    'palau'               :  'PW' ,
    'pennsylvania'        :  'PA' ,
    'puerto rico'         :  'PR' ,
    'rhode island'        :  'RI' ,
    'south carolina'      :  'SC' ,
    'south dakota'        :  'SD' ,
    'tennessee'           :  'TN' ,
    'texas'               :  'TX' ,
    'utah'                :  'UT' ,
    'vermont'             :  'VT' ,
    'virgin island'       :  'VI' ,
    'virginia'            :  'VA' ,
    'washington'          :  'WA' ,
    'west virginia'       :  'WV' ,
    'wisconsin'           :  'WI' ,
    'wyoming'             :  'WY' 
    }

    export default states;